### ISSUE TITLE
Move to an org

### ISSUE THREAD

**Issue by dblock** [txcrb/tax_cloud#36]
Coming from #35

**Comment by mrbiggred** [comment]
@dblock I submitted issue #39 before i noticed this.  Did you move the repository to an organisation?  If not is there a working fork of this project?  Thanks.

**Comment by dblock** [comment]
I haven't been involved in this gem for a while, but I am happy to help. Nothing has moved, it's still very much here and we should be maintaining it. Happy to cut a release when I get to it if nobody else will cc: @drewtempelmeyer.

**Comment by ghepting** [comment]
bump on this. happy to be a contributor if we're not letting this turn into abandonware :)

**Comment by drewtempelmeyer** [comment]
I'll prioritize this.

**Comment by dblock** [comment]
@drewtempelmeyer want to do it?

**Comment by drewtempelmeyer** [comment]
@dblock @ghepting done!

**Comment by ghepting** [comment]
Nice – if you want to add me as a contributor of the org I'm happy to stay active on this for a while. I just got everything working this morning (with a temporary work-around on the tax rate not being exposed in any APIs currently) with Square APIs in the custom ecommerce application I'm working on, so got a pretty good overview on everything at this point.
